theme: jekyll-theme-cayman

# Setup
title:        Blog
tagline:      
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       México Mozilla Club
  url:        http://mexicomozillaclub.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
